version: '3'
services:
  uplink1:
    build: source
    ports:
        - 8001:8001
    environment:
        - SERVER_PORT=8001
    restart: on-failure
    command: ['python3', 'Uplink1.py']
  uplink2:
    build: source
    ports:
        - 9001:9001
    environment:
        - SERVER_PORT=9001
    restart: on-failure
    command: ['python3', 'Uplink2.py']